In [1]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from floater.generators import FloatSet
from xmitgcm import open_mdsdataset

In [2]:
%matplotlib inline

In [3]:
ds = open_mdsdataset('/data/scratch/rpa/global_lagrangian/run', iters=None)
ds

/home/cz2397/xmitgcm/xmitgcm/utils.py:314: UserWarning: Not sure what to do with rlev = L
  warnings.warn("Not sure what to do with rlev = " + rlev)


<xarray.Dataset>
Dimensions:  (XC: 3600, XG: 3600, YC: 1600, YG: 1600, Z: 1, Zl: 1, Zp1: 2, Zu: 1)
Coordinates:
  * XC       (XC) >f4 0.05 0.15 0.25 0.35 0.45 0.55 0.65 0.75 0.85 0.95 1.05 ...
  * YC       (YC) >f4 -79.95 -79.85 -79.75 -79.65 -79.55 -79.45 -79.35 ...
  * XG       (XG) >f4 -2.77556e-17 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 ...
  * YG       (YG) >f4 -80.0 -79.9 -79.8 -79.7 -79.6 -79.5 -79.4 -79.3 -79.2 ...
  * Z        (Z) >f4 -50.0
  * Zp1      (Zp1) >f4 0.0 -100.0
  * Zu       (Zu) >f4 -100.0
  * Zl       (Zl) >f4 0.0
    rA       (YC, XC) >f4 2.15699e+07 2.15699e+07 2.15699e+07 2.15699e+07 ...
    dxG      (YG, XC) >f4 1930.58 1930.58 1930.58 1930.58 1930.58 1930.58 ...
    dyG      (YC, XG) >f4 11117.7 11117.7 11117.7 11117.7 11117.7 11117.7 ...
    Depth    (YC, XC) >f4 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    rAz      (YG, XG) >f4 2.14637e+07 2.14637e+07 2.14637e+07 2.14637e+07 ...
    dxC      (YC, XG) >f4 1940.13 1940.13 1940.13 1940.13 1940.13 1

In [57]:
lon = ds.XC.values
lat = ds.YC.values
land_mask = ds.hFacC.values==1

In [58]:
land_mask.shape

(1600, 3600)

In [59]:
len(lat)

1600

In [5]:
model_grid = {'lon': lon, 'lat': lat, 'land_mask': land_mask}

In [8]:
lon

array([  5.00000007e-02,   1.50000006e-01,   2.50000000e-01, ...,
         3.59750000e+02,   3.59850006e+02,   3.59950012e+02], dtype=float32)

In [18]:
lon = np.linspace(0, 8, 9, dtype=np.float32)
lon

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.], dtype=float32)

In [60]:
lon = np.linspace(0, 8, 9)
lon

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [61]:
lat = np.linspace(-4, 4, 9)
lat

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [62]:
land_mask = np.zeros(81)
for i in range(81):
    if i%2 == 0:
        land_mask[i] = 1

In [70]:
land_mask = land_mask==1
land_mask

array([[ True, False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True]], dtype=bool)

In [71]:
land_mask.shape = (len(lat), len(lon))

In [72]:
model_grid = {'lon': lon, 'lat': lat, 'land_mask': land_mask}
model_grid

{'land_mask': array([[ True, False,  True, False,  True, False,  True, False,  True],
        [False,  True, False,  True, False,  True, False,  True, False],
        [ True, False,  True, False,  True, False,  True, False,  True],
        [False,  True, False,  True, False,  True, False,  True, False],
        [ True, False,  True, False,  True, False,  True, False,  True],
        [False,  True, False,  True, False,  True, False,  True, False],
        [ True, False,  True, False,  True, False,  True, False,  True],
        [False,  True, False,  True, False,  True, False,  True, False],
        [ True, False,  True, False,  True, False,  True, False,  True]], dtype=bool),
 'lat': array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.]),
 'lon': array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])}

In [78]:
fs = FloatSet(xlim=(0,8), ylim=(-4,4), dx=1, dy=1, model_grid=model_grid)

In [80]:
land_mask.shape

(9, 9)

In [81]:
fs.get_rectmesh()

(array([ 0.5,  2.5,  7.5,  4.5,  5.5,  7.5,  1.5,  2.5,  4.5,  3.5,  5.5,
         6.5,  0.5,  3.5,  5.5,  6.5,  1.5,  2.5,  4.5,  4.5,  5.5,  7.5,
         0.5,  2.5,  7.5]),
 array([-3.5, -3.5, -3.5, -2.5, -2.5, -2.5, -1.5, -1.5, -1.5, -0.5, -0.5,
        -0.5,  0.5,  0.5,  0.5,  0.5,  1.5,  1.5,  1.5,  2.5,  2.5,  2.5,
         3.5,  3.5,  3.5]))

In [82]:
fs.Nx

8

In [87]:
npart = np.linspace(1, 41, 41, dtype=np.int32)
npart

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41], dtype=int32)

In [85]:
npart

range(1, 41)

In [96]:
values = np.random.random(41)
values

array([ 0.81626901,  0.9508684 ,  0.87242671,  0.11621154,  0.51689762,
        0.04361354,  0.13720915,  0.39928626,  0.80898694,  0.20243389,
        0.30646224,  0.01356323,  0.86932917,  0.44087223,  0.20077988,
        0.531861  ,  0.16029231,  0.4903793 ,  0.65358242,  0.71598271,
        0.79263997,  0.06434687,  0.0853139 ,  0.50608982,  0.46786177,
        0.00752236,  0.5037569 ,  0.36262163,  0.8829054 ,  0.56053556,
        0.64412335,  0.35265166,  0.51671127,  0.49045811,  0.76327537,
        0.16966524,  0.52372685,  0.78054784,  0.01414083,  0.03551927,
        0.82204959])

In [89]:
import random

In [83]:
fs.Ny

8

### hex

In [ ]:
fs_hex = FloatSet(xlim=(0, 360), ylim=(-80, 70), dx=1/32, dy=1/32, model_grid=model_grid)

In [ ]:
fs_hex.get_hexmesh()

In [ ]:
path_hex = '/data/scratch/cz2397/rclv-eddies/flt_ini_pos_hex.global.32deg_f4'

In [ ]:
pkl_path_hex = path_hex + '.pkl'

In [ ]:
fs_hex.to_pickle(pkl_path_hex)

In [ ]:
fs_hex_test = FloatSet(load_path=pkl_path_hex)

In [ ]:
fs_hex_test.ocean_bools

In [ ]:
bin_path_hex = path_hex + '.bin'

In [ ]:
fs_hex.to_mitgcm_format(bin_path_hex, mesh='hex', read_binary_prec=32)

In [ ]:
floats_hex = np.fromfile(bin_path_hex, dtype='>f4')

In [ ]:
total_num_hex = len(floats_hex)
total_num_hex

In [ ]:
float_num_hex = total_num_hex//9
float_num_hex

In [ ]:
floats_hex.shape = (float_num_hex, 9)
floats_hex.shape

In [ ]:
x_hex = floats_hex[:, 2]
y_hex = floats_hex[:, 3]

In [ ]:
sns.set()
plt.rcParams['figure.figsize'] = (16, 8)
plt.scatter(x_hex[::100], y_hex[::100], edgecolor='none', s=1)
plt.xlim([0, 360])
plt.ylim([-80, 70])
plt.show()

### rec

In [ ]:
fs_rec = FloatSet(xlim=(0, 360), ylim=(-80, 70), dx=0.03125, dy=0.03125, model_grid=model_grid)

In [ ]:
fs_rec.get_rectmesh()

In [ ]:
path_rec = '/data/scratch/cz2397/rclv-eddies/flt_ini_pos_rec.global.32deg_f4'

In [ ]:
pkl_path_rec = path_rec + '.pkl'

In [ ]:
fs_rec.to_pickle(pkl_path_rec)

In [ ]:
fs_rec_test = FloatSet(load_path=pkl_path_rec)

In [ ]:
fs_rec_test.ocean_bools

In [ ]:
bin_path_rec = path_rec + '.bin'

In [ ]:
fs_rec.to_mitgcm_format(bin_path_rec, mesh='rect', read_binary_prec=32)

In [ ]:
floats_rec = np.fromfile(bin_path_rec, dtype='>f4')

In [ ]:
total_num_rec = len(floats_rec)
total_num_rec

In [ ]:
float_num_rec = total_num_rec//9
float_num_rec

In [ ]:
floats_rec.shape = (float_num_rec, 9)
floats_rec.shape

In [ ]:
x_rec = floats_rec[:, 2]
y_rec = floats_rec[:, 3]

In [ ]:
sns.set()
plt.rcParams['figure.figsize'] = (16, 8)
plt.scatter(x_rec[::100], y_rec[::100], edgecolor='none', s=1)
plt.xlim([0, 360])
plt.ylim([-80, 70])
plt.show()